"""
Initial

Revision ID: 3850981f672c
Revises: 728839411b45
Create Date: 2024-10-17 19:40:26.093312

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3850981f672c"
down_revision = "728839411b45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comics",
        sa.Column("comic_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("explain_url", sa.String(), nullable=True),
        sa.Column("click_url", sa.String(), nullable=True),
        sa.Column("is_interactive", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("comic_id", name=op.f("pk_comics")),
    )
    op.create_index(
        "uq_comic_number_if_not_extra",
        "comics",
        ["number"],
        unique=True,
        postgresql_where=sa.text("number IS NOT NULL"),
    )
    op.create_index(
        "uq_comic_title_if_extra",
        "comics",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("number IS NULL"),
    )
    op.create_table(
        "images",
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("temp_image_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore[no-untyped-call]
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("image_id", name=op.f("pk_images")),
    )
    op.create_index(
        "ix_image_entity_type_entity_id",
        "images",
        ["entity_type", "entity_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("from_explainxkcd", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("tag_id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "comic_tag_association",
        sa.Column("comic_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comic_id"],
            ["comics.comic_id"],
            name=op.f("fk_comic_tag_association_comic_id_comics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
            name=op.f("fk_comic_tag_association_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("comic_id", "tag_id", name=op.f("pk_comic_tag_association")),
    )
    op.create_table(
        "translations",
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("comic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("tooltip", sa.String(), nullable=False),
        sa.Column("transcript", sa.String(), nullable=False),
        sa.Column("translator_comment", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("searchable_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comic_id"],
            ["comics.comic_id"],
            name=op.f("fk_translations_comic_id_comics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("translation_id", name=op.f("pk_translations")),
    )
    op.create_index(
        "ix_translations_searchable_text",
        "translations",
        ["searchable_text"],
        unique=False,
        postgresql_using="pgroonga",
    )
    op.create_index(
        "uq_translation_if_published",
        "translations",
        ["language", "comic_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_translation_if_published",
        table_name="translations",
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    op.drop_index(
        "ix_translations_searchable_text", table_name="translations", postgresql_using="pgroonga"
    )
    op.drop_table("translations")
    op.drop_table("comic_tag_association")
    op.drop_table("tags")
    op.drop_index("ix_image_entity_type_entity_id", table_name="images", postgresql_using="btree")
    op.drop_table("images")
    op.drop_index(
        "uq_comic_title_if_extra", table_name="comics", postgresql_where=sa.text("number IS NULL")
    )
    op.drop_index(
        "uq_comic_number_if_not_extra",
        table_name="comics",
        postgresql_where=sa.text("number IS NOT NULL"),
    )
    op.drop_table("comics")
    # ### end Alembic commands ###
