"""create_translation_table

Revision ID: 9718046cbdb5
Revises: c29f9de54121
Create Date: 2023-12-19 23:28:34.529595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9718046cbdb5"
down_revision = "c29f9de54121"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("issue_number", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tooltip", sa.String(), nullable=True),
        sa.Column("transcript", sa.String(), nullable=True),
        sa.Column("news_block", sa.String(), nullable=True),
        sa.Column("images", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_number"],
            ["comics.issue_number"],
            name=op.f("fk_translations_issue_number_comics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_number", "id", name=op.f("pk_translations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translations")
    # ### end Alembic commands ###
