"""Add unique version per translation constraint

Revision ID: 3d9047b8aad9
Revises: 6cde2744cfc2
Create Date: 2024-01-15 04:35:50.796004

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d9047b8aad9"
down_revision = "6cde2744cfc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_version_per_translation",
        "translation_images",
        ["version", "translation_id"],
        unique=True,
        postgresql_where=sa.text("translation_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_version_per_translation",
        table_name="translation_images",
        postgresql_where=sa.text("translation_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
