"""Image Set Null

Revision ID: 7ef46139ba59
Revises: f27a1b2af73f
Create Date: 2024-01-02 13:27:22.593757

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '7ef46139ba59'
down_revision = 'f27a1b2af73f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_translation_images_translation_id_translations', 'translation_images', type_='foreignkey')
    op.create_foreign_key(op.f('fk_translation_images_translation_id_translations'), 'translation_images', 'translations', ['translation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_translation_images_translation_id_translations'), 'translation_images', type_='foreignkey')
    op.create_foreign_key('fk_translation_images_translation_id_translations', 'translation_images', 'translations', ['translation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
