"""Add translation title constraint

Revision ID: 9c3ef9e68654
Revises: b4d9e09f6423
Create Date: 2024-01-10 19:51:08.032525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9c3ef9e68654'
down_revision = 'b4d9e09f6423'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_non_draft', table_name='translations', postgresql_where='(NOT is_draft)')
    op.create_index('ix_unique_translation_title_not_draft', 'translations', ['language', 'title'], unique=True, postgresql_where=sa.text('NOT is_draft'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_translation_title_not_draft', table_name='translations', postgresql_where=sa.text('NOT is_draft'))
    op.create_index('ix_unique_non_draft', 'translations', ['comic_id', 'language'], unique=True, postgresql_where='(NOT is_draft)')
    # ### end Alembic commands ###
