default_language_version:
  python: python3.12
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.0
#    hooks:
#      - id: mypy

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.4.9
#    hooks:
#      - id: ruff
#        args: [ --fix, --exit-non-zero-on-fix ]
#
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: []
