default_language_version:
  python: python3.12
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.1
#    hooks:
#      - id: mypy

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.5.2
#    hooks:
#      - id: ruff
#        args: [ --fix, --exit-non-zero-on-fix ]
#      - id: ruff-format
