services:

  bot:
    container_name: telexkcdbot-bot
    build: bot
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - core

  api:
    container_name: telexkcdbot-api
    build: api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}
    healthcheck:
      test: curl -f http://api:{API_PORT} || exit 1
      interval: 1s
      timeout: 1s
      start_period: 10s
      retries: 10
    restart: unless-stopped
    profiles:
      - core
      - api

  db:
    container_name: telexkcdbot-postgres
    image: onjin/alpine-postgres:13.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1s
      timeout: 1s
      start_period: 10s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    profiles:
      - core
      - api

