version: '3.9'

services:
  api:
    container_name: telexkcdbot-api
    build: ./src/api
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    command: ['./wait-for-it.sh', 'db:${DB_PORT}', '--', "python", 'server.py']
  bot:
    container_name: telexkcdbot-bot
    build: ./src/bot
    ports:
      - '${BOT_PORT}:${BOT_PORT}'
    depends_on:
      - api
      - db
    env_file:
      - .env
    restart: always
    command: ['./wait-for-it.sh', 'api:${API_PORT}', '--', 'python', '__main__.py']
  db:
    container_name: telexkcdbot-postgres
    image: onjin/alpine-postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    restart: always

volumes:
  postgres_data:
