services:

  api:
    container_name: app.api
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
    command: poetry run api
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    links:
      - postgres


  postgres:
    container_name: app.postgres
    image: groonga/pgroonga:3.2.2-alpine-16-slim
#    command: -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "appdb"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
#      - ./.configs/postgresql.conf:/etc/postgresql.conf
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U admin -d appdb
      interval: 1s
      timeout: 1s
      start_period: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - backend


volumes:
  pg-data: {}

networks:
  backend:
    driver: bridge
    name: backend
