services:

  api:
    container_name: app.api
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
      - ./static:/app/static
      - ./.tmp:/app/.tmp
    command: poetry run api
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
  #    healthcheck:
  #      test: curl -fsSL http://localhost:8000/api/healthcheck
  #      interval: 10s
  #      timeout: 60s
  #      retries: 5
  #      start_period: 10s

  tg_bot:
    container_name: app.tg_bot
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
    command: poetry run tg_bot
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  worker:
    container_name: app.worker
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
      - ./static:/app/static
    command: poetry run faststream run --factory backend.main.broker:create_app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  postgres:
    container_name: app.postgres
    image: groonga/pgroonga:3.2.2-alpine-16-slim
    #    command: -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "appdb"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      #      - ./.configs/postgresql.conf:/etc/postgresql.conf
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U admin -d appdb
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend

  migrations:
    container_name: app.migrations
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
    command: poetry run alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    restart: no
    networks:
      - backend

  prepopulation:
    container_name: app.prepopulation
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      PYTHONPATH: .:./apps/backend/src
      CONFIG_PATH: /app/.configs/backend/config.toml
    volumes:
      - ./.configs/backend/config.toml:/app/.configs/backend/config.toml:ro
      - ./static:/app/static
      - ./.tmp:/app/.tmp
    command: bash -c "poetry run cli scrape_and_upload_origin --end=200 && 
                      poetry run cli scrape_and_upload_translations &&
                      poetry run cli extract_and_upload_prescraped_translations"
    depends_on:
      postgres:
        condition: service_healthy
    restart: no
    networks:
      - backend

  nats:
    container_name: app.nats
    image: nats:2.10.18
    restart: unless-stopped
    ports:
      - 4222:4222
    command: '-js'
    networks:
      - backend


volumes:
  pg-data: { }
  tmp-dir: { }
  static-dir: { }

networks:
  backend:
    driver: bridge
    name: backend
