[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "telexkcdbot"
version = "1.0.0"
description = "A functional asynchronous telegram-bot for handy reading xkcd comics."
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/coryphoenixxx/telexkcdbot"

[tool.poetry.dependencies]
python =  "^3.10"
aiofiles = "*"
aiogram = "^2.22.1"
aiohttp = "*"
aioschedule = " "
aiosignal = "*"
async-timeout = "*"
asyncpg = "*"
attrs = "*"
Babel = "*"
beautifulsoup4 = "*"
bs4 = "*"
certifi = "*"
chardet = "*"
charset-normalizer = "*"
colorama = "*"
frozenlist = "*"
googletrans = "^3.1.0a0"
h11 = "*"
h2 = "*"
hpack = "*"
hstspreload = "*"
httpcore = "*"
httpx = "*"
hyperframe = "*"
idna = "*"
loguru = "*"
lxml = "*"
multidict = "*"
numpy = "*"
pytz = "*"
rfc3986 = "*"
sniffio = "*"
soupsieve = "*"
toml = "*"
tqdm = "*"
typing-extensions = "*"
urllib3 = "*"
win32-setctime = "*"
yarl = "*"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
black = "^22.8.0"
pytest = "^7.1.3"
mypy = "^0.971"
mypy-extensions = "^0.4.3"
Flake8-pyproject = "^1.1.0.post0"
autoflake = "^1.5.3"



[tool.autoflake]
check = false
recursive = true
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true

[tool.isort]
profile = "black"
src_paths = ["telexkcdbot"]

[tool.black]
line-length = 120

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401']
max-line-length = 120
max-complexity = 12

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
