[tool.poetry]
name = "telexkcdbot"
version = "1.0.0"
description = "A functional asynchronous telegram-bot for handy reading xkcd comics."
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/coryphoenixxx/telexkcdbot"

[tool.poetry.dependencies]
python =  "^3.10"
aiofiles = "*"
aiogram = "^2.22.1"
aiohttp = "*"
aioschedule = "*"
aiosignal = "*"
async-timeout = "*"
asyncpg = "*"
attrs = "*"
Babel = "*"
beautifulsoup4 = "*"
bs4 = "*"
certifi = "*"
chardet = "*"
charset-normalizer = "*"
colorama = "*"
frozenlist = "*"
googletrans = "^3.1.0a0"
h11 = "*"
h2 = "*"
hpack = "*"
hstspreload = "*"
httpcore = "*"
httpx = "*"
hyperframe = "*"
idna = "*"
loguru = "*"
lxml = "*"
multidict = "*"
mypy = "*"
mypy-extensions = "*"
numpy = "*"
pytz = "*"
rfc3986 = "*"
sniffio = "*"
soupsieve = "*"
toml = "*"
tqdm= "*"
typing-extensions = "*"
urllib3 = "*"
win32-setctime = "*"
yarl = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"

[tool.isort]
line_length = 120
src_paths = ["telexkcdbot"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
