[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "telexkcdbot"
version = "1.0.0"
description = "A functional asynchronous telegram-bot for handy reading xkcd comics."
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/coryphoenixxx/telexkcdbot"

[tool.poetry.dependencies]
python =  "^3.10"
aiohttp = "^3.8.1"
async-timeout = "^4.0.2"
attrs = "^22.1.0"
aiosignal = "^1.2.0"
charset-normalizer = "^2.1.1"
frozenlist = "^1.3.1"
idna = "^2.10"
multidict = "^6.0.2"
yarl = "^1.8.1"
python-decouple = "^3.6"

[tool.poetry.group.bot.dependencies]
aiofiles = "^22.1.0"
aiogram = "^2.22.1"
aioschedule = "^0.5.2"
asyncpg = "^0.26.0"
Babel = "^2.9.1"
beautifulsoup4 = "^4.11.1"
bs4 = "^0.0.1"
certifi = "^2022.6.15.1"
chardet = "^3.0.4"
colorama = "^0.4.5"
googletrans = "^3.1.0a0"
h11 = "^0.9.0"
h2 = "^3.2.0"
hpack = "^3.0.0"
hstspreload = "^2022.9.1"
httpcore = "^0.9.1"
httpx = "^0.13.3"
hyperframe = "^5.2.0"
loguru = "^0.6.0"
lxml = "^4.9.1"
numpy = "^1.23.3"
pytz = "^2022.2.1"
rfc3986 = "^1.5.0"
sniffio = "^1.3.0"
soupsieve = "^2.3.2.post1"
toml = "^0.10.2"
tqdm = "^4.64.1"
urllib3 = "^1.26.12"
win32-setctime = "^1.1.0"

[tool.poetry.group.api.dependencies]
asyncpg = "^0.26.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1.3"

[tool.autoflake]
check = false
recursive = true
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true

[tool.isort]
profile = "black"
src_paths = ["telexkcdbot"]

[tool.black]
line-length = 120

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401']
max-line-length = 120
max-complexity = 12

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
