[tool.poetry]
name = "telexkcdbot"
version = "1.0.0"
description = "A functional asynchronous telegram-bot for handy reading xkcd comics."
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/coryphoenixxx/telexkcdbot"

[tool.poetry.dependencies]
python = '3.10.8'

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1.3"

[tool.autoflake]
check = false
recursive = true
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true

[tool.isort]
profile = "black"
src_paths = ["telexkcdbot"]

[tool.black]
line-length = 120

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401', 'F841']
max-line-length = 120
max-complexity = 12

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ['src/bot/tests', 'src/api/tests']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
