[tool.poetry]
name = "telexkcdbot"
version = "1.0.0"
description = "telexkcdbot"
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
repository = "https://github.com/coryphoenixxx/telexkcdbot"
packages = [
    { include = "shared", from = "src" },
    { include = "api", from = "src" },
    { include = "data", from = "src" },
]


[tool.poetry.scripts]
scrape_origin_and_upload = "scripts.scrape_origin_and_upload:main"
scrape_translations_and_upload = "scripts.scrape_translations_and_upload:main"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.api.dependencies]
fastapi = "^0.110.0"
uvicorn = { extras = ["standard"], version = "^0.27" }
sqlalchemy = "^2.0.23"
asyncpg = "^0.29.0"
python-multipart = "^0.0.6"
orjson = "^3.9.10"
pydantic-settings = "^2.1.0"
aiofiles = "^23.2.1"
alembic = "^1.13.0"
uvloop = "^0.19.0"
filetype = "^1.2.0"
imagesize = "^1.4.1"
python-slugify = "^8.0.1"
httptools = "^0.6.1"
aiohttp = "^3.9.1"
aiodns = "^3.1.1"
aiohttp-retry = "^2.8.3"
gunicorn = "^21.2.0"
faststream = { extras = ["nats"], version = "^0.4" }
pydantic = "^2.5"
nats-py = "2.7.0"
adaptix = "^3.0.0b3"
argon2-cffi = "^23.1.0"


[tool.poetry.group.scraper.dependencies]
aiohttp = "^3.9"
uvloop = "^0.19.0"
faust-cchardet = "^2.1.19"
aiodns = "^3.0.0"
lxml = "^5.1.0"
beautifulsoup4 = "^4.12.2"
aiohttp-retry = "^2.8.3"
rich = "^13.7.0"
asyncclick = "^8.1.7.1"


[tool.poetry.group.image_processor.dependencies]
faststream = { extras = ["nats"], version = "^0.4" }
pillow = "^10.1.0"
pydantic = "^2.5"
nats-py = "2.7.0"


[tool.poetry.group.bot.dependencies]
aiogram = "^3.4.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3"
ruff = "^0.3"
black = "^24"


[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = ["-s", "-v"]
pythonopath = [".venv/bin"]


[tool.ruff]
lint.ignore-init-module-imports = true
lint.select = [
    "B",
    "E",
    "W",
    "F",
    "N",
    "COM",
    "I",
    "ASYNC",
    "PL",
    "RUF",
    "SIM",
    "C90",
    "ARG",
    "T20",
    "C4",
    "UP",
    "G004"
]
lint.ignore = [
    "N805",
    "PLR0913",
    "PLR2004",
    "B904",
    "PLR0911",
    "PLR0912",
    "C901",
    "B008",
    "ARG001",
    "RUF013",
    "N999",
]
lint.fixable = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "N",
    "Q",
    "S",
    "T",
    "W",
    "ANN",
    "ARG",
    "BLE",
    "COM",
    "DJ",
    "DTZ",
    "EM",
    "ERA",
    "EXE",
    "FBT",
    "ICN",
    "INP",
    "ISC",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLF",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT"
]
lint.unfixable = []

show-fixes = true

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
lint.per-file-ignores = { }

line-length = 100

lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"


[tool.ruff.lint.mccabe]
max-complexity = 10


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
