"""Add search vector field.

Revision ID: c723c235396e
Revises: a521957a3185
Create Date: 2024-02-16 16:12:04.126884

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c723c235396e"
down_revision = "a521957a3185"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("translations", sa.Column("searchable_text", sa.String(), nullable=False))
    op.create_index(
        "ix_translations_searchable_text",
        "translations",
        ["searchable_text"],
        unique=False,
        postgresql_using="pgroonga",
        postgresql_where=sa.text("NOT is_draft"),
    )
    op.drop_column("translations", "transcript_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translations",
        sa.Column(
            "transcript_text",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            default="",
        ),
    )
    op.drop_index(
        "ix_translations_searchable_text",
        table_name="translations",
        postgresql_using="pgroonga",
        postgresql_where=sa.text("NOT is_draft"),
    )
    op.drop_column("translations", "searchable_text")
    # ### end Alembic commands ###
