"""Add searchable text field.

Revision ID: 3297650c9163
Revises: a521957a3185
Create Date: 2024-02-17 06:30:07.870575

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "3297650c9163"
down_revision = "a521957a3185"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("CREATE EXTENSION IF NOT EXISTS pgroonga;"))

    op.add_column("translations", sa.Column("searchable_text", sa.String(), nullable=False))
    op.create_index(
        "ix_translations_searchable_text",
        "translations",
        ["searchable_text"],
        unique=False,
        postgresql_using="pgroonga",
    )
    op.drop_column("translations", "transcript_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translations",
        sa.Column("transcript_text", sa.VARCHAR(), autoincrement=False),
    )
    op.drop_index(
        "ix_translations_searchable_text", table_name="translations", postgresql_using="pgroonga",
    )
    op.drop_column("translations", "searchable_text")
    # ### end Alembic commands ###
