"""
Add tag slug and blacklisted columns

Revision ID: 54a5f6e75c3e
Revises: 165dbbb4ba3c
Create Date: 2024-06-27 02:21:47.332106

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "54a5f6e75c3e"
down_revision = "165dbbb4ba3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("slug", sa.String(), nullable=False))
    op.add_column("tags", sa.Column("is_blacklisted", sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f("uq_tags_slug"), "tags", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_tags_slug"), "tags", type_="unique")
    op.drop_column("tags", "is_blacklisted")
    op.drop_column("tags", "slug")
    # ### end Alembic commands ###
