[api]
host = "0.0.0.0"
port = 8000


[bot]
token = ""
admin_id = 1234567890
run_method = "POLLING"

[bot.app]
host = "0.0.0.0"
port = 5000

[bot.webhook]
url = ""
secret_token = ""
path = "/bot/webhook"


[db]
host = "localhost"
port = 5432
dbname = "appdb"
user = "admin"
password = "password"
echo = false
pool_size = 100


[fs]
temp_dir = "...data/temp"
static_dir = "...data/static"
prescraped_dir = "...data/prescraped"
upload_max_size = 10485760


[nats]
url = "nats://localhost:4222"
