[api]
host = "0.0.0.0"
port = 8000


[bot]
token = ""
admin_id = 1234567890
run_method = "WEBHOOK"

[bot.app]
host = "0.0.0.0"
port = 5000

[bot.webhook]
url = ""
secret_token = "secret"
path = "/bot/webhook"


[db]
host = "app.postgres"
port = 5432
dbname = "appdb"
user = "admin"
password = "password"
echo = false
pool_size = 100


[fs]
temp_dir = "/app/data/temp"
static_dir = "/app/data/static"
prescraped_dir = "/app/data/prescraped"
upload_max_size = 10485760


[nats]
url = "nats://app.nats:4222"
