[app]
upload_max_size = 10485760
file_storage = "fs"
temp_dir = ".../data/temp"


[api]
host = "0.0.0.0"
port = 8000


[bot]
token = ""
admin_id = 1234567890
run_method = "POLLING"

[bot.app]
host = "0.0.0.0"
port = 5000

[bot.webhook]
url = ""
secret_token = ""
path = "/bot/webhook"


[cli]
prescraped_dir = ".../data/prescraped"


[db]
host = "localhost"
port = 5432
dbname = "appdb"
user = "admin"
password = "password"
echo = false
pool_size = 100


[fs]
root_dir = ".../data/static"


[s3]
bucket = "xkcdworld-static"
endpoint_url = "http://localhost:9000"
aws_access_key_id = "user"
aws_secret_access_key = "password"


[nats]
url = "nats://localhost:4222"
