"""Initial commit

Revision ID: 3217f0613a27
Revises:
Create Date: 2023-08-07 10:01:27.375170

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '3217f0613a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comics',
                    sa.Column('comic_id', sa.SmallInteger(), nullable=False),
                    sa.Column('publication_date', sa.String(), nullable=False),
                    sa.Column('is_specific', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('comic_id'),
                    )
    op.create_table('users',
                    sa.Column('tg_id', sa.BigInteger(), nullable=False),
                    sa.Column('tg_lang_code', sa.SmallInteger(), nullable=True),
                    sa.Column('ui_lang', sa.String(), nullable=True),
                    sa.Column('rus_only_mode', sa.Boolean(), nullable=True),
                    sa.Column('joined_at', sa.Date(), nullable=True),
                    sa.Column('last_activity_at', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('tg_id'),
                    )
    op.create_table('comic_translations',
                    sa.Column('comic_id', sa.SmallInteger(), nullable=False),
                    sa.Column('language_code', sa.String(length=2), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('comment', sa.String(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('transcript', sa.Text(), nullable=False),
                    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(),
                              sa.Computed("to_tsvector('english', title || ' ' || comment || ' ' || transcript)",
                                          persisted=True), nullable=True),
                    sa.ForeignKeyConstraint(['comic_id'], ['comics.comic_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('comic_id', 'language_code'),
                    sa.UniqueConstraint('title', 'image_url', 'comment', name='uix__comics'),
                    )
    op.create_index('ix__comics___ts_vector__', 'comic_translations', ['search_vector'], unique=False,
                    postgresql_using='gin')
    op.create_table('explanations',
                    sa.Column('exp_id', sa.SmallInteger(), nullable=False),
                    sa.Column('comic_id', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['comic_id'], ['comics.comic_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('exp_id'),
                    )
    op.create_table('favorites',
                    sa.Column('comic_id', sa.SmallInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['comic_id'], ['comics.comic_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('comic_id', 'user_id'),
                    sa.UniqueConstraint('comic_id', 'user_id', name='uix__favorite'),
                    )
    op.create_table('watch_history',
                    sa.Column('wh_id', sa.SmallInteger(), nullable=False),
                    sa.Column('comic_id', sa.SmallInteger(), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['comic_id'], ['comics.comic_id']),
                    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id']),
                    sa.PrimaryKeyConstraint('wh_id'),
                    sa.UniqueConstraint('comic_id', 'user_id', name='uix__watch_history'),
                    )
    op.create_table('explanation_translations',
                    sa.Column('exp_id', sa.SmallInteger(), nullable=False),
                    sa.Column('language_code', sa.String(length=2), nullable=False),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['exp_id'], ['explanations.exp_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('exp_id', 'language_code'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanation_translations')
    op.drop_table('watch_history')
    op.drop_table('favorites')
    op.drop_table('explanations')
    op.drop_index('ix__comics___ts_vector__', table_name='comic_translations', postgresql_using='gin')
    op.drop_table('comic_translations')
    op.drop_table('users')
    op.drop_table('comics')
    # ### end Alembic commands ###
