[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "telexkcdbot-api"
version = "1.0.0"
description = "telexkcdbot API microservice"
authors = ["coryphoenixxx <coryphoenixxx@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/coryphoenixxx/telexkcdbot/api"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.3"
aiosignal = "^1.2.0"
loguru = "^0.7.0"
sqlalchemy = "^2.0"
asyncpg = "^0.28"
alembic = "^1.11.1"
sqlalchemy-utils = "^0.41.1"
jsonschema = "^4.17"
pydantic-settings = "^2.0.1"
pydantic = "^2.0.2"
python-decouple = "^3.8"
